script  soapui installation

diff --git a/install-soapui b/install-soapui
--- a/install-soapui
+++ b/install-soapui
@@ -1,9 +1,33 @@
 #!/bin/bash
-
 source ./install.source.sh
 
-function main(){
-  local -r url="https://b537910400b7ceac4df0-22e92613740a7dd1247910134033c0d1.ssl.cf5.rackcdn.com/soapui/5.3.0/SoapUI-x64-5.3.0.sh"
-  download "url"
+function main() {
+  # local -r extension=".tar.gz"
+  local -r extension=".sh";
   
+  local -r base_url="https://s3.amazonaws.com/downloads.eviware"
+  local xml;
+  xml=$(wget -q -O - "${base_url}?list-type=2&prefix=soapuios");
+  if [[ "$?" -ne 0 ]]; then
+    echo "[ERROR] Unable to query link to latest soapui version." >&2;
+    exit 1;
+  fi
+
+  local relative_url;
+  relative_url=$(xmllint --xpath "(//*[local-name()='Key' and starts-with(text(), 'soapuios') and contains(text(),'linux') and contains(text(), '.tar.gz')])[last()]/text()" - <<< "${xml}");
+  if [[ "$?" -ne 0 ]]; then
+    echo "[ERROR] Unable to parse link to latest soapui version." >&2;
+    exit 1;
+  fi
+
+  local -r url="${base_url}/${relative_url}";
+  echo "${url}";
+  #$(wget "${url}");
+  #if [[ "$?" -ne 0 ]]; then
+  #  echo "[ERROR] Unable to download soapui (${url})" >&2;
+  #  exit 1;
+  #fi
+  download "${url}" "soapui" "bin/soapui.sh";
 }
+
+main "$@"
